GET http://localhost:3000/

###

GET http://localhost:3000/search?query=nex

###

POST http://localhost:3000/
Content-Type: application/json

{
    "content": "hotdog",
    "postId": "6"
}

###

POST http://localhost:3000/post

###

DELETE http://localhost:3000/post/